### ISSUE TITLE
PAYMENT_METHOD_TOKENIZATION_TYPE_DIRECT implementation issue

### ISSUE THREAD

**Issue by hbgopikrishna** [android-pay/paymentsapi-quickstart#6]
Hello Greetings,

I'm trying to implement the android pay in my application. But my payment processor is not supporting Android pay so, I'm working on direct payment process using the PAYMENT_METHOD_TOKENIZATION_TYPE_DIRECT method. For this I need on public key for that I am using the below link to create public key 
https://developers.google.com/payments/payment-data-cryptography#encrypt-spec but the application is always showing request failed error dialogue in android.
![requestfailderror](https://user-images.githubusercontent.com/19644209/36149960-d514f3d6-10e7-11e8-907f-939bb83770b9.png)

**Comment by fstanis** [comment]
Hi, thank you for your interest - please check [Test and deploy](https://developers.google.com/payments/test-and-deploy) for more information on how to get production access - most notably, you need to follow the link in that article to sign up.

**Comment by hbgopikrishna** [comment]
I'm getting this error due to the publicKey. Can you please guide me how can I create correct publicKey to successful integration of android pay in my application.

**Comment by fstanis** [comment]
Please reach out to [Google Pay support](https://services.google.com/fb/forms/googlepaymentAPI/) for integration questions - this issue tracker is reserved for problems with the sample app itself.
